#pragma once

#include "variables.h"
#include "passing_arrays_to_functions.h"
#include "same_tree.h"
#include "linked_list.h"
#include "merge_ranges.h"
#include "plus_one.h"
#include "add_two_numbers_from_linked_lists.h"
#include "pascal_triangle.h"
#include "copy_by_value_vs_copy_by_reference.h"
#include "simple_tree.h"
#include "binary_search_tree.h"
#include "avl_tree.h"
#include "basic_sale_item_ops.h"
#include "simple_thread.h"
#include "for_ex.h"
#include "compound_declaration.h"
#include "conversions.h"
#include "double_pointer.h"
#include "declarations.h"

void testVectorGrades();
void testCDeclarationsAndStringManipulations();
void testMultipleCharReplacementTechniques();
void testCharComparison();
void testMultiDimensionArrays();
void testPointerTraversal();
void testSquare();