#pragma once

enum LoadingState {
	TEST_VARIABLE_GLOBAL_UNINITIALIZED,
	TEST_VARIABLE_GLOBAL_VS_LOCAL,
	TEST_SCOPE_VARIABLES,
	TEST_CONSTANT_VARIABLES,
	TEST_PASS_BY_SIZED_ARRAY,
	TEST_PASS_BY_UNSIZED_ARRAY,
	TEST_PASS_BY_ARRAY_POINTER,
	TEST_VECTOR,
	TEST_LEET_CODE_SAME_TREE,
	TEST_PRINT_LINKED_LIST,
	TEST_MERGED_RANGES,
	TEST_PLUS_ONE,
	TEST_ADD_TWO_NUMBERS_FROM_LINKED_LISTS,
	TEST_PASCAL_TRIANGLE,
	TEST_RETURN_BY_REFERENCE_OUT_OF_SCOPE,
	TEST_COPY_BY_VALUE,
	TEST_COPY_BY_REFERENCE,
	TEST_TREE_SIZE,
	TEST_TRAVERSE_TREE_IN_ORDER,
	TEST_TRAVERSE_TREE_PRE_ORDER,
	TEST_TRAVERSE_TREE_POST_ORDER,
	TEST_TRAVERSE_TREE_LEVEL_ORDER,
	TEST_FIND_MINIMUM_IN_BST,
	TEST_INSERT_IN_BST,
	TEST_INSERT_IN_BST_V2,
	TEST_CALCULATE_MAXIMUM_DEPTH,
	TEST_AVL_INSERT
};

void StartSample(LoadingState sample);