#pragma once

enum LoadingState {
	TEST_PASS_BY_SIZED_ARRAY,
	TEST_PASS_BY_UNSIZED_ARRAY,
	TEST_PASS_BY_ARRAY_POINTER,
	TEST_VECTOR,
	TEST_LEET_CODE_SAME_TREE,
	TEST_PRINT_LINKED_LIST,
	TEST_MERGED_RANGES,
	TEST_PLUS_ONE,
	TEST_ADD_TWO_NUMBERS_FROM_LINKED_LISTS,
	TEST_PASCAL_TRIANGLE,
};

void StartSample(LoadingState sample);